### ISSUE TITLE
NoSuchMethodError Crash Upon Clicking "Config" Button

### ISSUE THREAD

**Issue by Ommina** [JoJoDeveloping/ItemTextureExporter#1]
The first issue!  I feel so warm.

Forge 28.1.102

I followed the "How to Use" instructions; found the mod, "Config" lit up, I click it, and the client crashes.  Additionally, and I hesitate to guess whether is is related or not, but there is a "Failed to load a valid ResourcePackInfo" warning on starting the client.  So far, I've elected to ignore the warning.

https://pastebin.com/YyM0UNwY

Edit: I removed _all_ other mods from the mods directory, but the crash persist.

**Comment by Lykrast** [comment]
Also happens on forge 28.1.113.

**Comment by JoJoDeveloping** [comment]
Fixed in the latest upload.
