### ISSUE TITLE
Failed to load a valid ResourcePackInfo

### ISSUE THREAD

**Issue by Lykrast** [JoJoDeveloping/ItemTextureExporter#2]
This warning happens when launching the game with the mod. It seem to still work but there's still the warning.

![image](https://user-images.githubusercontent.com/8684850/72058342-3b6ff200-32d0-11ea-8140-8a840b5cf6a9.png)

Forge 28.1.113, mod version 1.2.1.

**Comment by JoJoDeveloping** [comment]
Thanks for reporting, I'll fix it.

**Comment by skylorbeck** [comment]
@JoJoDeveloping Hey sorry to bump old things but I'm getting this error on my mod and I have no idea what is causing it. Did you figure it out?

**Comment by JoJoDeveloping** [comment]
Your pack.mcmeta is most likely broken, see the fixing commit in this repo
